Feature/iammiracle/custom register
lifeaid/project-template pull request #34
Opened 2019-06-13 22:13 UTC by iammiracle

What does this PR do?

- The User is able to Register which is can be used to authenticate via Auth0
- Upon the click of Login, the user is redirected to Auth0 to login, also forgot password is handled by auth0.

2019-06-14 07:10 UTC, enyeInc commented on components/About/AboutPage.js
> +                    <br />
do noe abuse `br` tag use css to create new lines and space

2019-06-14 07:11 UTC, enyeInc commented on components/About/AboutPage.js
> +                        <p>Dedication</p>
you should use an array of object and map over it to create the `animation-content`

2019-06-14 07:12 UTC, enyeInc commented on components/Register/RegisterPage.js
> +/* eslint space-before-function-paren:0 */
remove eslint disbales

2019-06-14 07:16 UTC, enyeInc commented on components/Register/RegisterPage.js
> +                            />
you are repeating `TextField` too many times, find a way to way over the values that you to create these elements

2019-06-14 07:17 UTC, enyeInc commented on components/Register/RegisterPage.js
> +    const classes = useStyles();
do not use this pattern, we are not using in-line styles because they get recreated every time that this component is re-instantiated

2019-06-14 07:20 UTC, enyeInc commented
@iammiracle please only keep changes for a specific ticket in your PR. I saw that you were fixing some spacing and indent issues in the code. Although this is good, it should have been done in another PR, because it is distracting from the actual changes meant for this PR

2019-06-14 07:20 UTC, enyeInc requested changes
Minor clean up before approval

2019-06-17 11:30 UTC, EngrEric commented on components/Register/RegisterPage.js
> +                                      /* i used {e => {handler}(e.target.value)} but show error */
Yes this `{e => {handler}(e.target.value)} ` will throw an error because handler here is a string not a method.

2019-06-17 15:29 UTC, Way2nnadi commented on components/Register/RegisterPage.js
> +                                      onChange={e => getStateFunction(e.target.value, { name })}
this piece of code is broken, did you test to see if it works?

2019-06-17 15:29 UTC, Way2nnadi commented on components/Register/RegisterPage.js
> +                            /> */}
deleted unused code

2019-06-17 16:01 UTC, Way2nnadi approved these changes
LGTM

2019-06-19 10:29 UTC, Merdoth approved these changes

2019-06-19 11:46 UTC, merged