Initial model setup
lifeaid/project-template pull request #6
Opened 2019-05-05 15:46 UTC by codemutatio

**What does this PR do?**

- Application Model setup

- Database CRUD operation

2019-05-05 16:02 UTC, EngrEric commented on server/controllers/aidControllers.js
> +    });
destructure this code
```const { 
        aidTitle, 
        aidIntro,
        aidDescription,
       imageLink,
       videoLink } = req.body;```

2019-05-05 16:26 UTC, EngrEric reviewed
Looks good but aren't you leveraging the async/await paradigm.

2019-05-05 17:08 UTC, enyeInc commented
@codemutatio Go through each one of your controllers and like eric said leverage `async/await` pattern (https://javascript.info/async-await).

2019-05-05 21:50 UTC, enyeInc commented on server/controllers/aidControllers.js
> +        console.log(req.body);
remove `console.log`

2019-05-05 21:52 UTC, enyeInc commented on server/controllers/aidControllers.js
> +            const foundAids = await db.find(queryText);
why are you passing an empty object to `db.find`?

2019-05-05 21:52 UTC, enyeInc commented on server/controllers/aidControllers.js
> +			_id: req.params.aidId,
change this to `_id: req.params.id`

2019-05-05 21:55 UTC, enyeInc commented on server/controllers/promise.js
> +      return new Promise((resolve, reject) => {
you do not need to wrap these functions in a promise, they are already promises.
```
return Aid.find(param);
```
is all you need to do

2019-05-05 21:59 UTC, enyeInc commented on server/controllers/aidControllers.js
> +          return res.status(400).send(error);
the status code for errors in a server is `500` not `400` make this change in all your filles

2019-05-05 22:00 UTC, enyeInc commented
@codemutatio this is almost ready to be merge. Make the final changes and additional use this module to define your error status code
- https://www.npmjs.com/package/http-status-codes

For example:
```
import HttpStatus from 'http-status-codes';
const { INTERNAL_SERVER_ERROR }  = HttpStatus;
...
catch(error) {
    return res.status(INTERNAL_SERVER_ERROR).send(error);
}
```

2019-05-05 22:00 UTC, enyeInc requested changes
Need to fix more syntax

2019-05-06 04:30 UTC, enyeInc commented on server/controllers/reportControllers.js
> +
delete unused `lines 60-61`

2019-05-06 04:32 UTC, enyeInc commented
@codemutatio Your code looks great just one last thing for you to add for it to be excellent. You need to standardize the data that is being returned from your backend. This is listed in the enye conventions. The standard that we use is JSend (https://github.com/omniti-labs/jsend). I left an example in the comments above. Adjust your endpoints to conform to this specification and you will have my approval to merge this down

2019-05-06 04:36 UTC, enyeInc commented on server/controllers/aidControllers.js
> +          });
Use JSend specification (https://github.com/omniti-labs/jsend) when sending out of your endpoints
```
...
const aid = await db.create(queryText);
return res.status(CREATED).send({
    status: 'success',
    data: { aid, message: 'Aid successfully created' },
});
...

2019-05-06 08:31 UTC, iammiracle reviewed
I think once the JSend is fixed, we can merge this.

2019-05-06 17:12 UTC, Way2nnadi commented on server/controllers/aidControllers.js
> +            });
i gave you an example of how you should name your data variables and the overall syntax. Do not send an `UpdaredAid` or a `foundAid`, just send `aid` or `aids`. Also use single quotations not double. that should have been enforced in your eslint

2019-05-06 17:12 UTC, Way2nnadi commented on server/controllers/aidControllers.js
> +                data: {"Aid": aid}
`data: { aid }`

2019-05-06 17:14 UTC, Way2nnadi commented on server/controllers/aidControllers.js
> +                data: {"Aids": aids}
In javascript first letters of keys in objects are lower case => `data: { aids }`

2019-05-06 17:14 UTC, Way2nnadi commented on server/controllers/aidControllers.js
> +                data : { "title" : errors }
single quotations

2019-05-06 17:16 UTC, Way2nnadi commented on server/controllers/aidControllers.js
> +                data : { "title" : errors }
title can not be errors just send the error `(not errors)` object => `data: { error }`. Change that in this file and the other files. Send the error inside of the data not as a message

2019-05-06 17:16 UTC, Way2nnadi commented on server/controllers/reportControllers.js
> +        data: {"Reports": reports},
wrong

2019-05-06 17:17 UTC, Way2nnadi commented on server/controllers/reportControllers.js
> +        data: {"Report": report}
fix this

2019-05-06 17:20 UTC, Way2nnadi commented on server/controllers/aidControllers.js
> +                message : error
where are you getting this `error` variable from? check this in this file and the other files, you have an syntax error

2019-05-06 17:22 UTC, Way2nnadi commented on server/controllers/aidControllers.js
> +                message : error
`error` is an object so i would say do something like this
```
...
    status : 'error',
    message : getStatusText(INTERNAL_SERVER_ERROR)
    error,
...
```

2019-05-07 07:39 UTC, enyeInc approved these changes
Looks good to me

2019-05-07 08:17 UTC, iammiracle approved these changes

2019-05-07 11:05 UTC, merged